name: Deploy to EC2 via Git Pull

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 (git pull & build)
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu/GapBotApp

            echo "Pull latest master"
            git pull origin master

            LOCAL_HASH=$(git rev-parse HEAD)

            if [ ! -f .last_deploy_commit ]; then
              echo "$LOCAL_HASH" > .last_deploy_commit
            fi

            LAST_DEPLOY_COMMIT=$(cat .last_deploy_commit)

            if [ "$LOCAL_HASH" != "$LAST_DEPLOY_COMMIT" ]; then
              echo "Detecting changes since $LAST_DEPLOY_COMMIT"

              changed_files=$(git diff --name-only "$LAST_DEPLOY_COMMIT" "$LOCAL_HASH")
              echo "Changed files:"
              echo "$changed_files"

              if echo "$changed_files" | grep -q "^next-app/"; then
                echo "Next-app changed: Building..."
                cd next-app
                npm install
                npm run build
                pm2 restart 2
                cd ..
              fi

              if echo "$changed_files" | grep -q "^server/"; then
                echo "Server changed: Restarting PM2..."
                pm2 restart 0
              fi

              if echo "$changed_files" | grep -q "^next-app/"; then
                echo "Restarting nginx..."
                sudo systemctl restart nginx
              fi

              echo "$LOCAL_HASH" > .last_deploy_commit
              echo "Deployment complete."
            else
              echo "No changes detected. Skipping build and restart."
            fi
          EOF