name: Deploy to Production Server

on:
  push:
    branches:
      - master # master 브랜치에서만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to Production Server
        uses: appleboy/scp-action@v0.2.0
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_KEY }}
          source: "."
          target: "/var/www/prod-app"

      - name: Restart production app
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_KEY }}
          script: |
            cd /var/www/prod-app
            npm install
            pm2 restart prod-app
